[2025-06-17 03:17:34,631] INFO in services: User authenticated successfully: test2@gmail.com
[2025-06-17 03:33:03,046] WARNING in services: authentication fail for email: test2@gjjmail.com
[2025-06-17 03:34:27,924] INFO in services: New user created: test2@gjjmail.com
[2025-06-17 03:51:18,654] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 03:51:18,656] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/signup: Object of type RequestValidationError is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\routing.py", line 346, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\app\core\exception_handler.py", line 19, in validation_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 182, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 45, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 185, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RequestValidationError is not JSON serializable
[2025-06-17 03:51:43,488] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 03:57:06,688] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 04:03:45,598] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 04:03:45,599] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/signup: Object of type ValueError is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\routing.py", line 346, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\app\core\exception_handler.py", line 19, in validation_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 182, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 45, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 185, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValueError is not JSON serializable
[2025-06-17 04:05:26,854] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 04:05:26,855] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/signup: Object of type ValueError is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\routing.py", line 346, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\app\core\exception_handler.py", line 19, in validation_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 182, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 45, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\responses.py", line 185, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValueError is not JSON serializable
[2025-06-17 04:07:06,300] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-17 04:07:15,324] INFO in services: New user created: test3@gmail.com
[2025-06-17 18:11:04,466] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'model_attributes_type', 'loc': ('body',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': b'{\r\n    "email": "test1@gmail.com",\r\n    "password":"Password@1",\r\n    "name": "testing"\r\n}'}]
[2025-06-17 18:11:17,718] INFO in services: New user created: test1@gmail.com
[2025-06-17 18:12:19,174] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-17 18:15:02,299] INFO in services: New user created: admin@gmail.com
[2025-06-17 18:16:45,182] INFO in services: User authenticated successfully: admin@gmail.com
[2025-06-17 18:17:57,303] INFO in services: Fetched every product
[2025-06-17 18:31:43,724] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/admin/products: [{'type': 'missing', 'loc': ('body', 'description'), 'msg': 'Field required', 'input': {'name': 'Shoes', 'price': '500', 'stock': '20', 'category': 'footwear', 'image_url': 'https://example.com/images/shoes.jpg'}}]
[2025-06-17 18:33:48,517] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/admin/products: [{'type': 'missing', 'loc': ('body', 'description'), 'msg': 'Field required', 'input': {'name': 'Shoes', 'price': 500, 'stock': 20, 'category': 'footwear', 'image_url': 'https://example.com/images/shoes.jpg'}}]
[2025-06-17 18:36:46,134] ERROR in services: Error creating product: (psycopg2.ProgrammingError) can't adapt type 'HttpUrl'
[SQL: INSERT INTO products (name, description, price, stock, category, image_url) VALUES (%(name)s, %(description)s, %(price)s, %(stock)s, %(category)s, %(image_url)s) RETURNING products.id]
[parameters: {'name': 'Shoes', 'description': None, 'price': 500.0, 'stock': 20, 'category': 'footwear', 'image_url': HttpUrl('https://example.com/images/shoes.jpg')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-06-17 18:39:00,264] INFO in services: Product created with ID 1
[2025-06-17 18:39:47,015] INFO in services: Fetched every product
[2025-06-17 18:42:09,658] INFO in services: Fetched every product
[2025-06-17 18:42:21,322] INFO in services: Product created with ID 2
[2025-06-17 18:43:02,830] INFO in services: Fetched every product
[2025-06-17 18:45:49,092] INFO in services: Product 2 updated
[2025-06-17 18:46:28,153] INFO in services: Fetched every product
[2025-06-17 19:08:26,133] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-17 19:25:04,466] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:25:20,360] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-17 19:25:29,710] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:25:55,871] INFO in services: Filtered products: total=2, returned=0, page=2, category=None
[2025-06-17 19:26:12,637] INFO in services: Filtered products: total=2, returned=0, page=9, category=None
[2025-06-17 19:26:19,502] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:27:31,981] INFO in services: Search for 'iph' returned 0 results
[2025-06-17 19:27:59,983] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/products/search: [{'type': 'missing', 'loc': ('query', 'keyword'), 'msg': 'Field required', 'input': None}]
[2025-06-17 19:28:10,393] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:28:20,511] INFO in services: Search for 'sha' returned 0 results
[2025-06-17 19:28:24,787] INFO in services: Search for 'sh' returned 1 results
[2025-06-17 19:28:32,614] INFO in services: Search for 'ip' returned 0 results
[2025-06-17 19:28:59,494] INFO in services: Search for 'iphone' returned 0 results
[2025-06-17 19:29:05,855] INFO in services: Search for 'jenga' returned 0 results
[2025-06-17 19:29:12,271] INFO in services: Search for 'dfhjvbjsd' returned 0 results
[2025-06-17 19:30:50,221] INFO in services: Search for '' returned 2 results
[2025-06-17 19:30:58,323] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/products/search: [{'type': 'missing', 'loc': ('query', 'keyword'), 'msg': 'Field required', 'input': None}]
[2025-06-17 19:31:04,877] INFO in services: Search for '' returned 2 results
[2025-06-17 19:32:00,031] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:32:41,096] INFO in services: User authenticated successfully: admin@gmail.com
[2025-06-17 19:32:52,946] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:42:13,192] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:42:34,850] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:42:43,960] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:42:48,357] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:42:57,177] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:43:03,674] INFO in services: Filtered products: total=2, returned=2, page=1, category=None
[2025-06-17 19:49:22,787] INFO in services: Filtered products: total=0, returned=0, page=1, category=food
[2025-06-17 20:01:08,005] WARNING in services: authentication fail for email: admin@gmail.com
[2025-06-17 20:01:13,174] INFO in services: User authenticated successfully: admin@gmail.com
[2025-06-17 20:02:39,034] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-17 20:03:08,065] INFO in services: User 1 has an empty cart.
[2025-06-17 20:14:09,982] INFO in services: Added new product 1in user 1's cart.
[2025-06-17 20:16:22,777] INFO in services: Added new product 2in user 1's cart.
[2025-06-17 20:17:23,666] INFO in services: Updated cart item quantity for user 1 with product 1
[2025-06-17 20:17:32,731] WARNING in services: Requested quantity 200 exceeds stock for product 2
[2025-06-17 20:17:37,432] WARNING in services: Requested quantity 200 exceeds stock for product 1
[2025-06-17 20:17:45,555] INFO in services: Updated cart item quantity for user 1 with product 1
[2025-06-17 20:19:22,999] INFO in services: Updated cart item quantity for user 1 with product 1
[2025-06-17 20:20:35,612] INFO in services: Updated cart item quantity for user 1 with product 1
[2025-06-17 20:20:41,447] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/cart/1: [{'type': 'greater_than', 'loc': ('body', 'quantity'), 'msg': 'Input should be greater than 0', 'input': 0, 'ctx': {'gt': 0}}]
[2025-06-17 20:20:55,300] INFO in services: Updated cart item quantity for user 1 with product 1
[2025-06-17 20:22:10,740] INFO in services: Deleted cart item for user 1 with product 1.
[2025-06-17 20:22:54,087] WARNING in services: Requested quantity 30 exceeds stock for product 1.
[2025-06-17 20:22:59,070] INFO in services: Added new product 1in user 1's cart.
[2025-06-17 20:25:04,062] INFO in services: User authenticated successfully: admin@gmail.com
[2025-06-17 20:26:17,785] INFO in services: Product 1 deleted
[2025-06-17 20:27:33,297] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-17 20:31:51,600] INFO in routes: User 1 placed order 1 successfully.
[2025-06-17 22:28:22,493] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one uppercase letter', 'input': 'password', 'ctx': {'error': ValueError('Password must contain at least one uppercase letter')}}]
[2025-06-17 22:30:11,476] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'enum', 'loc': ('body', 'role'), 'msg': "Input should be 'admin' or 'user'", 'input': 'moderator', 'ctx': {'expected': "'admin' or 'user'"}}]
[2025-06-17 22:30:39,298] INFO in services: New user created: hulk@gmail.com
[2025-06-18 03:00:08,707] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 03:00:34,914] INFO in services: User 1 has an empty cart.
[2025-06-18 03:00:58,286] INFO in services: Added new product 2in user 1's cart.
[2025-06-18 03:02:16,935] INFO in routes: User 1 placed order 2 successfully.
[2025-06-18 03:03:19,131] WARNING in services: Order 6 not found for user 1
[2025-06-18 03:11:33,674] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 03:11:39,773] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 03:12:24,716] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-18 03:46:38,222] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 03:48:39,956] INFO in services: User 1 has an empty cart.
[2025-06-18 03:49:37,915] WARNING in services: Password reset attempt for non-existing user: test@gmail.com
[2025-06-18 03:51:29,538] INFO in services: Password reset link sent to: test1@gmail.com
[2025-06-18 03:56:30,405] ERROR in exception_handler: Unhandled exception at http://localhost:8000/reset-password?token=9f99bf33-8974-4476-b2a7-c66ef7f93f3b: 404: Not Found
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 764, in app
    await self.default(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 650, in not_found
    raise HTTPException(status_code=404)
starlette.exceptions.HTTPException: 404: Not Found
[2025-06-18 03:57:07,273] ERROR in exception_handler: Unhandled exception at http://localhost:8000/reset-password?token=9f99bf33-8974-4476-b2a7-c66ef7f93f3b: 404: Not Found
[2025-06-18 03:58:06,199] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/reset-password: [{'type': 'value_error', 'loc': ('body', 'new_password'), 'msg': 'Value error, must have uppercase', 'input': 'newpassword', 'ctx': {'error': ValueError('must have uppercase')}}]
[2025-06-18 03:58:43,331] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/reset-password: [{'type': 'value_error', 'loc': ('body', 'new_password'), 'msg': 'Value error, must have uppercase', 'input': 'newpassword', 'ctx': {'error': ValueError('must have uppercase')}}]
[2025-06-18 03:58:43,332] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/reset-password: 'RequestValidationError' object has no attribute 'detail'
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\routing.py", line 346, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'value_error', 'loc': ('body', 'new_password'), 'msg': 'Value error, must have uppercase', 'input': 'newpassword', 'ctx': {'error': ValueError('must have uppercase')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\app\core\exception_handler.py", line 24, in validation_exception_handler
    "message": exc.detail,
               ^^^^^^^^^^
AttributeError: 'RequestValidationError' object has no attribute 'detail'
[2025-06-18 03:59:07,747] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/reset-password: [{'type': 'value_error', 'loc': ('body', 'new_password'), 'msg': 'Value error, must have uppercase', 'input': 'newpassword', 'ctx': {'error': ValueError('must have uppercase')}}]
[2025-06-18 03:59:29,195] INFO in services: Password reset successfully for user: test1@gmail.com
[2025-06-18 03:59:59,380] INFO in services: Password reset link sent to: test1@gmail.com
[2025-06-18 04:00:33,604] INFO in services: Password reset successfully for user: test1@gmail.com
[2025-06-18 04:00:41,595] WARNING in services: authentication fail for email: test1@gmail.com
[2025-06-18 04:00:41,599] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/signin: 401: Invalid email or password
[2025-06-18 04:00:47,790] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 13:15:02,333] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-18 13:31:02,482] ERROR in exception_handler: Unhandled exception at http://127.0.0.1:8000/auth/signup: ValueError() takes no keyword arguments
Traceback (most recent call last):
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\dependencies\utils.py", line 666, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\dependencies\utils.py", line 906, in request_body_to_args
    v_, errors_ = _validate_value_with_model_field(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\dependencies\utils.py", line 706, in _validate_value_with_model_field
    v_, errors_ = field.validate(value, values, loc=loc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\fastapi\_compat.py", line 129, in validate
    self._type_adapter.validate_python(value, from_attributes=True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\env\Lib\site-packages\pydantic\type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vinayak Khandelwal\Desktop\ecom_fastapi\app\auth\schemas.py", line 22, in strong_password
    raise ValueError(detail="Password must contain at least one digit")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ValueError() takes no keyword arguments
[2025-06-18 13:31:32,466] WARNING in exception_handler: Validation error at http://127.0.0.1:8000/auth/signup: [{'type': 'value_error', 'loc': ('body', 'password'), 'msg': 'Value error, Password must contain at least one digit', 'input': 'Password', 'ctx': {'error': ValueError('Password must contain at least one digit')}}]
[2025-06-18 13:57:09,717] INFO in services: User authenticated successfully: test1@gmail.com
[2025-06-18 13:57:38,061] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-18 13:58:24,252] INFO in services: Added new product 2in user 1's cart.
[2025-06-18 13:58:39,112] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-18 13:58:58,905] INFO in routes: User 1 placed order 3 successfully.
[2025-06-18 13:59:07,395] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-18 14:00:23,067] INFO in services: Filtered products: total=1, returned=1, page=1, category=None
[2025-06-18 14:08:52,139] INFO in services: Filtered products: total=5, returned=5, page=1, category=None
